version: '3.4'

services:
  ctdapi:
    image: ctdapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes: 
      - /:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro